/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservasi.tampilan;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Heni Ardiana
 */
public class menuutama extends javax.swing.JFrame {
    
    private DataDriver Driver;
    private DataBus Bus;
    private DataCostumer Costumer;
    private DataPemesanan Pemesanan;
    private DataPembayaran Pembayaran;
    private LapDataDriver Lap_Driver;
    private LapDataBus Lap_Bus;
    private LapDataCostumer Lap_Costumer;
    private LapDataPemesanan Lap_Pemesanan;
    private LapDataPembayaran Lap_Pembayaran;
    
    private void setJam(){
        ActionListener listener = new ActionListener (){
            
            @Override
            public void actionPerformed(ActionEvent evt){
                jam.setText(new WaktuSekarang ().getWkt ());
            }
        };
        new Timer(1000, listener).start();
    }
    private void ResetPusat(){
        try{
            DesktopPane.getSelectedFrame(). setClosed(true);
        }catch (Exception e){}
    }
    
    private void PusatBar(javax.swing.plaf.InternalFrameUI jif_f){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)jif_f).setNorthPane(null);
    }

    /**
     * Creates new form menuutama
     */
    public menuutama() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        DesktopPane = new DesktopPaneBackground();
        jLabel1 = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem13.setText("jMenuItem13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 5, 5));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pukul : ");

        jam.setText(new WaktuSekarang().getWkt());

        jLabel3.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal :");

        tgl.setText(new WaktuSekarang().getTgl());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jam)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tgl)
                .addGap(0, 1044, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jam)
                    .addComponent(jLabel3)
                    .addComponent(tgl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("User");

        jMenuItem1.setText("Lagout");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master Data");

        jMenuItem2.setText("Data Driver");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Data Bus");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem8.setText("Data Costumer");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu10.setText("Proses");

        jMenuItem9.setText("Data Pemesanan");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem9);

        jMenuItem16.setText("Data Pembayaran");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem16);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("Laporan");

        jMenuItem10.setText("Laporan Data Driver");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem10);

        jMenuItem12.setText("Laporan Data Bus");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem12);

        jMenuItem14.setText("Laporan Data Costumer");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem14);

        jMenuItem15.setText("Laporan Data Pemesanan");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem15);

        jMenuItem17.setText("Laporan Data Pembayaran");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem17);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
     try{
         ResetPusat();
         if (Driver==null ||Driver.isClosed()==true){
             Driver = new DataDriver();
             DesktopPane.add(Driver);
             }else{
                  Driver.toFront();
         }
         Driver.setVisible(true);
         Driver.setSelected(true);
         Driver.setSize(DesktopPane.getSize());
         PusatBar(Driver.getUI());
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Gagal Menampilkan Halaman Jabatan !");
     }
    
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try{
         ResetPusat();
         if (Bus==null ||Bus.isClosed()==true){
             Bus = new DataBus();
             DesktopPane.add(Bus);
             }else{
                  Bus.toFront();
         }
         Bus.setVisible(true);
         Bus.setSelected(true);
         Bus.setSize(DesktopPane.getSize());
         PusatBar(Bus.getUI());
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Gagal Menampilkan Halaman Jabatan !");
     }
    
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        try{
         ResetPusat();
         if (Costumer==null ||Costumer.isClosed()==true){
             Costumer = new DataCostumer();
             DesktopPane.add(Costumer);
             }else{
                  Costumer.toFront();
         }
         Costumer.setVisible(true);
         Costumer.setSelected(true);
         Costumer.setSize(DesktopPane.getSize());
         PusatBar(Costumer.getUI());
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Gagal Menampilkan Halaman Jabatan !");
     }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        try{
         ResetPusat();
         if (Pemesanan==null ||Pemesanan.isClosed()==true){
             Pemesanan = new DataPemesanan();
             DesktopPane.add(Pemesanan);
             }else{
                  Pemesanan.toFront();
         }
         Pemesanan.setVisible(true);
         Pemesanan.setSelected(true);
         Pemesanan.setSize(DesktopPane.getSize());
         PusatBar(Pemesanan.getUI());
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Gagal Menampilkan Halaman Jabatan !");
     }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        try{
         ResetPusat();
         if (Pembayaran==null ||Pembayaran.isClosed()==true){
             Pembayaran = new DataPembayaran();
             DesktopPane.add(Pembayaran);
             }else{
                  Pembayaran.toFront();
         }
         Pembayaran.setVisible(true);
         Pembayaran.setSelected(true);
         Pembayaran.setSize(DesktopPane.getSize());
         PusatBar(Pembayaran.getUI());
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Gagal Menampilkan Halaman Jabatan !");
     }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        try{
         ResetPusat();
         if (Lap_Driver==null ||Lap_Driver.isClosed()==true){
             Lap_Driver = new LapDataDriver();
             DesktopPane.add(Lap_Driver);
             }else{
                  Lap_Driver.toFront();
         }
         Lap_Driver.setVisible(true);
         Lap_Driver.setSelected(true);
         Lap_Driver.setSize(DesktopPane.getSize());
         PusatBar(Lap_Driver.getUI());
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Gagal Menampilkan Halaman Jabatan !");
     }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        try{
         ResetPusat();
         if (Lap_Bus==null ||Lap_Bus.isClosed()==true){
             Lap_Bus = new LapDataBus();
             DesktopPane.add(Lap_Bus);
             }else{
                  Lap_Bus.toFront();
         }
         Lap_Bus.setVisible(true);
         Lap_Bus.setSelected(true);
         Lap_Bus.setSize(DesktopPane.getSize());
         PusatBar(Lap_Bus.getUI());
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Gagal Menampilkan Halaman Jabatan !");
     }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
         try{
         ResetPusat();
         if (Lap_Costumer==null ||Lap_Costumer.isClosed()==true){
             Lap_Costumer = new LapDataCostumer();
             DesktopPane.add(Lap_Costumer);
             }else{
                  Lap_Costumer.toFront();
         }
         Lap_Costumer.setVisible(true);
         Lap_Costumer.setSelected(true);
         Lap_Costumer.setSize(DesktopPane.getSize());
         PusatBar(Lap_Costumer.getUI());
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Gagal Menampilkan Halaman Jabatan !");
     }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        try{
         ResetPusat();
         if (Lap_Pemesanan==null ||Lap_Pemesanan.isClosed()==true){
             Lap_Pemesanan = new LapDataPemesanan();
             DesktopPane.add(Lap_Pemesanan);
             }else{
                  Lap_Pemesanan.toFront();
         }
         Lap_Pemesanan.setVisible(true);
         Lap_Pemesanan.setSelected(true);
         Lap_Pemesanan.setSize(DesktopPane.getSize());
         PusatBar(Lap_Pemesanan.getUI());
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Gagal Menampilkan Halaman Jabatan !");
     }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        try{
         ResetPusat();
         if (Lap_Pembayaran==null ||Lap_Pembayaran.isClosed()==true){
             Lap_Pembayaran = new LapDataPembayaran();
             DesktopPane.add(Lap_Pembayaran);
             }else{
                  Lap_Pembayaran.toFront();
         }
         Lap_Pembayaran.setVisible(true);
         Lap_Pembayaran.setSelected(true);
         Lap_Pembayaran.setSize(DesktopPane.getSize());
         PusatBar(Lap_Pembayaran.getUI());
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Gagal Menampilkan Halaman Jabatan !");
     }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jam;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
